export interface KycDocument {
  id: string;
  userId: string;
  fullName?: string;
  email?: string;
  phone?: string;
  userKycStatus?: string;
  documentType: string;
  originalFilename?: string;
  mimeType?: string;
  fileHash?: string;
  cloudinaryAssetId?: string;
  cloudinaryPublicId?: string;
  cloudinaryResourceType?: string;
  cloudinaryDeliveryType?: string;
  cloudinaryVersion?: number;
  format?: string;
  fileSize?: number;
  documentUrl?: string;
  status: 'pending' | 'approved' | 'rejected';
  documentStatus?: 'pending_review' | 'approved' | 'rejected' | 'expired' | 'deleted';
  submittedAt: any;
  reviewedAt?: any;
  reviewedBy?: string;
  reviewerId?: string;
  reviewTimestamp?: any;
  reviewNotes?: string;
  rejectionReason?: string;
  notes?: string;
}
