import type { CSSProperties } from "react";

export const authStyles: Record<string, CSSProperties> = {
  page: {
    display: "flex",
    minHeight: "100vh",
    background:
      "linear-gradient(135deg, rgba(245, 247, 252, 0.98) 0%, rgba(238, 242, 251, 1) 100%)",
  },
  left: {
    flex: 1,
    background:
      "radial-gradient(circle at top left, rgba(27, 83, 226, 0.24), transparent 28%), #0A1628",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "48px",
    overflow: "hidden",
    position: "relative",
  },
  leftGlow: {
    position: "absolute",
    inset: "auto auto 12% -8%",
    width: 280,
    height: 280,
    borderRadius: "50%",
    background: "rgba(59, 130, 246, 0.14)",
    filter: "blur(18px)",
  },
  leftInner: {
    maxWidth: 440,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 40,
    position: "relative",
    zIndex: 1,
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  logoIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    background: "linear-gradient(135deg, #4B82FF 0%, #2563EB 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
    boxShadow: "0 10px 24px rgba(37, 99, 235, 0.26)",
  },
  logoText: {
    color: "#FFFFFF",
    fontWeight: 700,
    fontSize: 16,
  },
  headline: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  h1: {
    fontSize: 38,
    fontWeight: 700,
    color: "#FFFFFF",
    lineHeight: 1.2,
    letterSpacing: "-0.03em",
  },
  h1Blue: {
    color: "#3B82F6",
  },
  tagline: {
    fontSize: 15,
    color: "#8A9BB5",
    lineHeight: 1.7,
    maxWidth: 360,
  },
  statsRow: {
    display: "flex",
    gap: 22,
    flexWrap: "wrap",
  },
  statItem: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 90,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 700,
    color: "#FFFFFF",
  },
  statLabel: {
    fontSize: 12,
    color: "#8A9BB5",
  },
  right: {
    width: "50%",
    minWidth: 440,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  formShell: {
    width: "100%",
    maxWidth: 470,
    padding: 18,
    borderRadius: 30,
    background: "rgba(255, 255, 255, 0.7)",
    boxShadow: "0 24px 80px rgba(15, 23, 42, 0.08)",
    backdropFilter: "blur(12px)",
  },
  formCard: {
    width: "100%",
    background: "#FFFFFF",
    borderRadius: 22,
    padding: 36,
    boxShadow: "0 18px 60px rgba(15, 23, 42, 0.06)",
    border: "1px solid rgba(226, 232, 240, 0.9)",
  },
  formTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: "#0F172A",
    letterSpacing: "-0.03em",
  },
  formSub: {
    marginTop: 8,
    color: "#64748B",
    fontSize: 14,
  },
  label: {
    display: "block",
    fontSize: 14,
    fontWeight: 600,
    color: "#334155",
    marginBottom: 8,
  },
  helperAction: {
    border: "none",
    background: "transparent",
    color: "#3B82F6",
    fontSize: 13,
    fontWeight: 600,
    textDecoration: "none",
    cursor: "pointer",
    padding: 0,
  },
  inputWrap: {
    position: "relative",
  },
  eyeBtn: {
    position: "absolute",
    right: 14,
    top: "50%",
    transform: "translateY(-50%)",
    border: "none",
    background: "transparent",
    color: "#64748B",
    cursor: "pointer",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  errorBox: {
    background: "rgba(239, 68, 68, 0.08)",
    border: "1px solid rgba(239, 68, 68, 0.14)",
    color: "#B91C1C",
    borderRadius: 12,
    padding: "12px 14px",
    fontSize: 14,
    marginBottom: 18,
  },
  footerText: {
    marginTop: 26,
    textAlign: "center",
    color: "#64748B",
    fontSize: 15,
  },
  link: {
    color: "#3B82F6",
    textDecoration: "none",
    fontWeight: 700,
  },
  demoBox: {
    marginTop: 28,
    borderRadius: 16,
    border: "1px solid #E2E8F0",
    background: "#F8FAFC",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  demoLabel: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: 600,
  },
  demoValue: {
    fontSize: 13,
    color: "#0F172A",
    fontWeight: 700,
    lineHeight: 1.5,
  },
  spinner: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    border: "2px solid rgba(255,255,255,0.45)",
    borderTopColor: "#fff",
    display: "inline-block",
    animation: "spin 0.8s linear infinite",
  },
};
