export type DocumentCategory = 'kyc' | 'agreement';
export type DocumentStatus =
  | 'pending_review'
  | 'approved'
  | 'rejected'
  | 'expired'
  | 'deleted';

/** Whether the file was directly uploaded by a user or generated by the system (e.g. signed PDF). */
export type DocumentSource = 'user_upload' | 'system_generated';

/** The type of entity this document is linked to. */
export type DocumentRelatedEntityType = 'user' | 'loan' | 'legal_document';

export type ReviewInfo = {
  reviewedAt?: unknown;
  reviewedBy?: string;
  rejectionReason?: string;
  notes?: string;
};

export type DeleteInfo = {
  deletedAt?: unknown;
  deletedBy?: string;
  reason?: string;
};

export interface DocumentRecord {
  id: string;
  userId: string;
  fullName?: string;
  email?: string;
  phone?: string;
  userKycStatus?: string;
  category: DocumentCategory;
  documentType: string;
  originalFilename: string;
  mimeType: string;
  fileHash: string;
  cloudinaryAssetId: string;
  cloudinaryPublicId: string;
  cloudinaryResourceType: string;
  cloudinaryDeliveryType: string;
  cloudinarySecureUrl?: string;
  cloudinaryVersion?: number;
  format?: string;
  fileSize: number;
  uploadStatus: 'uploaded' | 'failed';
  status: DocumentStatus;
  /** Origin of the document – user-uploaded or backend-generated. Defaults to 'user_upload'. */
  source: DocumentSource;
  /** The type of entity this record is associated with (e.g. the loan or legal document it belongs to). */
  relatedEntityType?: DocumentRelatedEntityType;
  /** The Firestore ID of the related entity. */
  relatedEntityId?: string;
  /** Optional human-readable label shown in UIs (e.g. "Signed Loan Agreement – Loan #xyz"). */
  displayName?: string;
  uploadedAt: unknown;
  createdAt: unknown;
  updatedAt: unknown;
  deletedAt?: unknown;
  reviewerId?: string;
  reviewTimestamp?: unknown;
  reviewNotes?: string;
  review?: ReviewInfo;
  deletion?: DeleteInfo;
}
