'use strict';

const fs = require('fs');
const path = require('path');

function mdCell(value) {
  const text = value == null ? '' : String(value);
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function writeLoginDetails(fixtures, config) {
  const outputPath = path.resolve(
    __dirname,
    `login-details-${config.batchId}.md`,
  );
  const header = [
    'Role(s)',
    'User ID',
    'Email',
    'Phone',
    'Password',
    'Account Status',
    'KYC Status',
  ];
  const rows = fixtures.users.map((user) => [
    user.roles.join('|'),
    user.userId,
    user.email,
    user.phone,
    config.defaultPassword,
    user.accountStatus,
    user.kycStatus,
  ]);
  const separator = header.map(() => '---');
  const contents = [
    `# Login Details for ${config.batchId}`,
    '',
    'This file is generated by the bulk seed and contains the development logins',
    'for every seeded account.',
    '',
    `Default password: \`${config.defaultPassword}\``,
    '',
    '| ' + header.map(mdCell).join(' | ') + ' |',
    '| ' + separator.join(' | ') + ' |',
    ...rows.map(
      (row) =>
        '| ' +
        row
          .map(mdCell)
          .map((cell) => `\`${cell}\``)
          .join(' | ') +
        ' |',
    ),
    '',
  ].join('\n');

  fs.writeFileSync(outputPath, `${contents}\n`, { mode: 0o600 });
  fs.chmodSync(outputPath, 0o600);
  console.log(
    `Wrote ${rows.length} development login records to ${outputPath}.`,
  );
  return outputPath;
}

module.exports = { writeLoginDetails };
