export const BORROWER_DEFAULTS = {
  DEMO_BORROWER_ID: 'borrower_001',
  APPLICATION_AMOUNT: 50000,
  APPLICATION_TERM_MONTHS: 12,
  REPAYMENT_AMOUNT: 1000,
  STARTING_CREDIT_SCORE: 300,
  CREDIT_HISTORY_OFFSETS: [25, 10, 0],
} as const;

export const BORROWER_FLOW = {
  FEATURED_LOAN_LIMIT: 10,
  RECENT_ACTIVITY_LIMIT: 5,
  QR_CODE_PREFIX: 'QR',
} as const;

export const BORROWER_FILTER_LIMITS = {
  MIN_AMOUNT: 0,
  MAX_AMOUNT: Number.MAX_SAFE_INTEGER,
} as const;
